### ISSUE TITLE
The step by step wizard is not styled

### ISSUE THREAD

**Issue by hellais** [measurement-kit/ooniprobe-ios#40]
When opening the step by step wizard inside of netprobe the views are just vanilla HTML with no styling applied. They should feature the same styling as the rest of the content (at the very least the same font and same style for section headings).

Edit: it seems like the quiz is styled properly, so I am puzzled why that is getting the correct styling and the rest is not

**Comment by lorenzoPrimi** [comment]
fixed in https://github.com/measurement-kit/netprobe-ios/commit/bfcb452d401d1dfa4662609a277bc991d9031eab
but I will keep open this issue as now it doesn't support translation
