### ISSUE TITLE
Improve the user interface of the network ios client

### ISSUE THREAD

**Issue by hellais** [measurement-kit/ooniprobe-ios#43]
I am opening this ticket to show what is the current implementation of the user interface for the ooniprobe iOS and discuss potential improvements to the user interface before dedicated tickets for each improvement is created.

Here are screenshots for each of the views.
### Step 1 - Introduction

![img_0419](https://cloud.githubusercontent.com/assets/424620/19214999/c194c05a-8d91-11e6-882e-fd7c91c4d5c7.PNG)
### Step 2 - Risks

![img_0420](https://cloud.githubusercontent.com/assets/424620/19214997/c17db2c0-8d91-11e6-96a7-386d5396abc9.PNG)
### Step 3 - Quiz

![img_0421](https://cloud.githubusercontent.com/assets/424620/19214994/c17c4d72-8d91-11e6-922f-47d93e3775e7.PNG)
![img_0422](https://cloud.githubusercontent.com/assets/424620/19214993/c17bed82-8d91-11e6-9d35-5343ad99a118.PNG)
![img_0423](https://cloud.githubusercontent.com/assets/424620/19215001/c197caca-8d91-11e6-8ce7-1381290035d6.PNG)
### Step 4 - Configuration

![img_0424](https://cloud.githubusercontent.com/assets/424620/19214998/c17f5f8a-8d91-11e6-896d-efb186729f3e.PNG)
### Done

![img_0425](https://cloud.githubusercontent.com/assets/424620/19215004/c19a0fba-8d91-11e6-91fc-6b13e5107d52.PNG)
## Settings

![img_0432](https://cloud.githubusercontent.com/assets/424620/19214995/c17cae3e-8d91-11e6-8b5f-127c45e7ddd1.PNG)
### Select a test

![img_0428](https://cloud.githubusercontent.com/assets/424620/19215002/c19980fe-8d91-11e6-815b-9285bb645c23.PNG)
## Running tests

![img_0426](https://cloud.githubusercontent.com/assets/424620/19215003/c199df9a-8d91-11e6-87ad-553f4f7ec1f7.PNG)
![img_0427](https://cloud.githubusercontent.com/assets/424620/19215005/c1aeac9a-8d91-11e6-88f8-cfdeafd4e33a.PNG)
## Finished tests

![img_0429](https://cloud.githubusercontent.com/assets/424620/19214996/c17d1892-8d91-11e6-93b5-bd6eead04d82.PNG)
### Click on measurement with many inputs

![img_0430](https://cloud.githubusercontent.com/assets/424620/19215006/c1b37248-8d91-11e6-84ea-4858f7a9bb3c.PNG)
### Measurement - TCP Connect

![img_0431](https://cloud.githubusercontent.com/assets/424620/19215000/c1973010-8d91-11e6-99bf-cf0b890df1f3.PNG)

**Comment by Armed90** [comment]
Thanks for the next step

**Comment by lorenzoPrimi** [comment]
Here is how the app looks now.

## First start wizard
### Step 1 - Introduction

![simulator screen shot 17 nov 2016 17 11 05](https://cloud.githubusercontent.com/assets/1616097/20827743/3fea287a-b874-11e6-9d3e-ead75c07e121.png)
### Step 2 - Risks

![simulator screen shot 17 nov 2016 17 11 20](https://cloud.githubusercontent.com/assets/1616097/20827755/4bc3fa04-b874-11e6-9b63-a519a04fbb29.png)
### Step 3 - Quiz

![simulator screen shot 17 nov 2016 17 11 27](https://cloud.githubusercontent.com/assets/1616097/20827757/50ab3b04-b874-11e6-9f92-c9d90df5ef57.png)
### Step 4 - Configuration

![simulator screen shot 17 nov 2016 17 11 31](https://cloud.githubusercontent.com/assets/1616097/20827764/5772c9d4-b874-11e6-8f8c-4fb627daf284.png)
### Done

![simulator screen shot 17 nov 2016 17 11 45](https://cloud.githubusercontent.com/assets/1616097/20827780/5e8106f0-b874-11e6-8446-b508b3285b0b.png)
## Settings

![simulator screen shot 17 nov 2016 17 12 28](https://cloud.githubusercontent.com/assets/1616097/20827785/667bb7e2-b874-11e6-9b42-3620dadc33ed.png)
## Running tests

![simulator screen shot 17 nov 2016 17 12 07](https://cloud.githubusercontent.com/assets/1616097/20827800/75a66b5e-b874-11e6-96b6-eda182417160.png)
### Click on measurement with many inputs

![simulator screen shot 17 nov 2016 17 12 38](https://cloud.githubusercontent.com/assets/1616097/20827823/8b6fe654-b874-11e6-872d-77400170d6aa.png)
### Measurement - Web Connectivity

![simulator screen shot 17 nov 2016 17 12 44](https://cloud.githubusercontent.com/assets/1616097/20827830/91982e2e-b874-11e6-8072-d3cc6859a112.png)
### Info - Web Connectivity

![simulator screen shot 17 nov 2016 17 12 25](https://cloud.githubusercontent.com/assets/1616097/20827810/82403eda-b874-11e6-8379-2d0c799aec7c.png)
