### ISSUE TITLE
Informed consent should clarify link between OONI and NetProbe

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/ooniprobe-ios#45]
The informed consent as is is "good to go" but unclear to the extent that one not familiar with our family of projects would probably not understand what is OONI. I'd be careful and make sure that it's clarified that OONI is the project that develops NetProbe. Also, I will make sure that no mention is ever made to the "web user interface" within the informed consent because that also would raise eyebrows.

**Comment by lorenzoPrimi** [comment]
Closing as now the app is called ooniprobe
