### ISSUE TITLE
Generate input test-lists for first release

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/ooniprobe-ios#54]

**Comment by lorenzoPrimi** [comment]
https://github.com/OpenObservatory/ooni-resources/tree/master/assets
https://github.com/citizenlab/test-lists/tree/master/lists

**Comment by bassosimone** [comment]
@lorenzoPrimi, I think this is done now and we can close it, right?

**Comment by lorenzoPrimi** [comment]
sure
