### ISSUE TITLE
[minor] renamed tests got lost on upgrade

### ISSUE THREAD

**Issue by willscott** [measurement-kit/ooniprobe-ios#65]
My 'Past Tests' shows an NDT Speed test that I made before upgrading to latest version. Clicking to view it just shows 'Loading'.  The previous 'Invalid request line' test is able to load, so perhaps this has to do with the name changing?

**Comment by lorenzoPrimi** [comment]
Every time I release an update before the official release you should uninstall and reinstall, many times I change objects variables or names. No backcompatibility is guaranteed until official release.
