### ISSUE TITLE
No way to delete past tests

### ISSUE THREAD

**Issue by willscott** [measurement-kit/ooniprobe-ios#66]
There's no way to clear / clean past test results from the device.

**Comment by lorenzoPrimi** [comment]
Ops, I forgot to enable slide to delete

**Comment by lorenzoPrimi** [comment]
Fixed in https://github.com/measurement-kit/ooniprobe-ios/commit/68fb2a5f4b9d3a3d24006d35b24157392514571b

**Comment by willscott** [comment]
I'm not sure exactly what hit area this is on, but it seems really hard to trigger still. swiping on the item seemed to only work about 1/4 of the time.

**Comment by willscott** [comment]
I'm guessing the latest build now also includes aef8ae8a3c37deaded401dd347db1c43dcf49172.  Test deletion now seems to work reliably :+1:
