### ISSUE TITLE
Allow to see test logs

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/ooniprobe-ios#67]
As discussed in #61, I would be very happy if we have a way to see logs, because this would help me to understand and hopefully fix issues such as, e.g., #61 itself.

Thanks! <3

**Comment by lorenzoPrimi** [comment]
https://github.com/measurement-kit/ooniprobe-ios/commit/68fb2a5f4b9d3a3d24006d35b24157392514571b

**Comment by bassosimone** [comment]
Thank you!
